name: pages-build-deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure Safe Directory
      run: git config --global --add safe.directory /github/workspace

    - name: Install Missing Gems
      run: |
        gem 'rake', '12.3.3'
        gem 'jekyll-compose', '0.12.0'
        bundle install
        
    - name: Build with Jekyll
      uses: actions/jekyll-build-pages@v1.0.13
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
