name: pages-build-deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Fix Dubious Ownership
      run: git config --global --add safe.directory /github/workspace

    - name: Install Bundler
      run: gem install bundler

    - name: Install Gems
      run: bundle install

    - name: Build Site
      run: bundle exec jekyll build
